### ISSUE TITLE
Wrong filename for MacOS

### ISSUE THREAD

**Issue by nwoolls** [saro-lab/sap-jco-manager#1]
Based on my testing, the file name `sapjco3.jnilib` is wrong on MacOS. It needs to be `libsapjco3.jnilib`.

I managed to get things working by placing the files in `$HOME/Library/Java/Extensions/` with the JAR named as indicated in your current docs and the native library named as indicated above.

**Comment by marker-seoul** [comment]
Thank you, I'll fix it right away.
