### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no sapjco3 in java.library.path

### ISSUE THREAD

**Issue by windqdu** [saro-lab/sap-jco-manager#2]
linux系统需要将sapjco.so改名为libsapjco.so,要不然不认识这个共享库，依然会报：java.lang.UnsatisfiedLinkError: no sapjco3 in java.library.path

**Comment by J-SARO** [comment]
i do not understand chinese,
but UnsatisfiedLinkError occurs when the lib file cannot be found.
Search for UnsatisfiedLinkError on the Internet,
Try moving the ".so" file to the Linux java lib path.

**Comment by marker-seoul** [comment]
@windqdu 
i do not understand chinese,
but UnsatisfiedLinkError occurs when the library file (linux .so file) cannot be found.
Search for UnsatisfiedLinkError on the Internet
and try moving the ".so" file to the Linux java lib path.

**Comment by windqdu** [comment]
@J-SARO 
I am not very good at English。
I move sapjco.so to the linux lib path, but retain tip cannot found sapjco.so in 'java.library.path',later I rename sapjco.so to libsapjco.so,it is work.

**Comment by marker-seoul** [comment]
@windqdu 
Unfortunately, there is currently no infrastructure to test "SAP", so I can't.
So instead of renaming sapjco3.so, I added libsapjco3.so.

Thank you.

https://github.com/saro-lab/sap-jco-manager/commit/ad2d140d17bc0f5a08c2defe7d59bbe96674b89f

**Comment by windqdu** [comment]
@J-SARO 
You may move sapjco,jar and sapjco.so to a linux system,then execute "java -jar sapjco.jar" ,will show some information about sapjco.so verify。Rename sapjco.so to libsapjco.so ,again execute "java -jar sapjco.jar" command.You may look a difference information.

Best wishs you !

**Comment by marker-seoul** [comment]
@windqdu 
i will test libsapjco.so and sapjco.so by sapjco.jar

Thank you.
