### ISSUE TITLE
SAPJCO3.DLL  in Windows Server 2019 dont work

### ISSUE THREAD

**Issue by giodeber** [saro-lab/sap-jco-manager#3]
HelloI don't know, if you know why this error occurs.
the .dll & .jar file are in the libswt/win64 folder

java.lang.ExceptionInInitializerError: JCo initialization failed with java.lang.UnsatisfiedLinkError :C:\Users\Administrator\Downloads\pdi-ce-9.3.0.0-428\data-integration\libswt\win64\sapjco3.dll: %1 is not a valid Win32 application

windows server 2019
java jdk8
Pentaho ETL 9.3

best regards!

**Comment by giodeber** [comment]
in windows 8.1 x64 the  with the same dll and jar the error message is different


win 8.1 x64
java jdk8
Pentaho ETL 9.3

**Comment by ac-saro** [comment]
@emere01
Sorry for the late reply.
Can you try specifying the path manually like below?
run aguments
-Djava.library.path=c:\library\path

**Comment by marker-seoul** [comment]
@emere01
Sorry for the late reply.

Can you try one of the following?

@ 1
copy sapjco3.dll to C:\Windows\System32

@ 2
Copy sapjco3.dll to the same location as the .jar location.

@ 3
run with arguments (with jni path)
-Djava.library.path=c:\library\path

**Comment by giodeber** [comment]
Hello, thanks for your answer. It was solved by changing the plugin version to 64bit.
